# Generated by Django 3.0 on 2019-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('image', models.IntegerField()),
                ('good', models.IntegerField()),
                ('red', models.IntegerField()),
                ('readtext', models.CharField(max_length=100)),
            ],
        ),
    ]
